-- ============================================
-- COMPLETE MASTER CV - EVERYTHING
-- User: Linnea Moritz (da8ed517-3b67-4456-8831-6ed3cb7114ad)
-- Email: linneamoritzcv@gmail.com
--
-- CHRONOLOGICAL ORDER (most recent first)
-- AI TAGS for smart matching
-- ============================================

BEGIN;

-- ============================================
-- EDUCATION (4 schools with FULL details + transcripts)
-- ============================================
INSERT INTO user_education (user_id, school, location, degree, dates, bullets, sort_order) VALUES
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Minerva University',
 'San Francisco, USA',
 'B.S in Social Science, Economics and Business Administration (GPA: 3.6)',
 'Aug 2017 - Maj 2021',
 ARRAY[
   'Världens mest innovativa universitet för andra året i rad enligt World''s Universities with Real Impact (WURI)',
   'En antagningsgräns på 1.8% gör Minerva till det mest selektiva universitetet i USA',
   'Dubbelexamen i Business (koncentration: New Business Ventures) och Social Sciences (koncentration: Economics and Society)',
   'Studerade i 7 städer under fyra år: San Francisco, Seoul, Hyderabad, Berlin, Buenos Aires, London och Taipei',
   'Var mentor för 45 studenter i deras examensprojekt inom fem olika ämnen och branscher',
   'Kurser inkluderade: Market Dynamics, Global Enterprise Financial Strategy, Economic Tools, Business Operations, Research Methods, Complex Systems, Strategic Brand Leadership, Econometrics, Migration & Borders, Financial Planning & Budgeting',
   'Lärde mig Python, R, SQL och Machine Learning som del av ekonomi- och business-utbildningen',
   'Research/Internship Experience credit (IL199)',
   'Gjorde flera utflykter till företag i Silicon Valley under studietiden'
 ]::TEXT[],
 1),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'United World College Red Cross Nordics',
 'Flekke, Norge',
 'International Baccalaureate Bilingual Diploma - Engelska och Svenska (39 poäng, GPA: 3.85)',
 'Aug 2015 - Maj 2017',
 ARRAY[
   'IB Diploma med 39 poäng totalt (inklusive 2 bonuspoäng från Extended Essay och Theory of Knowledge)',
   'Blev utvald som en toppelev från Sverige och fick ett stipendium att studera på United World College',
   'Bodde med 200 elever från 96 olika länder och regioner',
   'Final grades: Chinese ab initio SL (6), Economics HL (6), Environmental Systems & Societies SL (7), Math Studies SL (6), Swedish Literature HL (6), Visual Art HL (6)',
   'Extended Essay i svensk litteratur: 36/36 poäng (perfekt betyg) - visar excellenta skrivfärdigheter',
   'Skolan har stort fokus på internationell fred och global förståelse',
   'Röda Korsets diplom: Guldutmärkelse för teamwork, frivilligarbete och ledarskap',
   'Över 100 timmar av volontärarbete',
   'Röda Korset Norge: 12 timmars grundläggande kurs i första hjälpen (Feb 2016)'
 ]::TEXT[],
 2),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'International School of the Stockholm Region',
 'Stockholm',
 'International Baccalaureate (Year 1)',
 'Aug 2014 - Maj 2015',
 ARRAY[
   'Genomförde det första året av International Baccalaureate-programmet i Stockholm',
   'Bred akademisk utbildning med betoning på internationell förståelse',
   'Utveckling av tvärvetenskapliga färdigheter'
 ]::TEXT[],
 3),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Per Brahe Gymnasium',
 'Jönköping',
 'Pre-IB',
 'Aug 2013 - Maj 2014',
 ARRAY[
   'Deltog i det obligatoriska Pre-IB-programmet som förberedelse för International Baccalaureate',
   'Grundlig förståelse för de akademiska och studiemässiga kraven inom IB'
 ]::TEXT[],
 4)
ON CONFLICT DO NOTHING;

-- ============================================
-- WORK EXPERIENCES (27 jobs in CHRONOLOGICAL ORDER)
-- With AI tags for smart matching
-- ============================================
INSERT INTO user_experiences (
  user_id, company, location, title,
  start_date, end_date, description,
  categories, sort_order,
  job_types, skill_level, environment_type, key_skills, industry_keywords
) VALUES
-- 2024-2025 (MOST RECENT)
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Profilgruppen',
 'Åseda, Sverige',
 'Anodiseringsoperatör (Feriearbete)',
 'Juli 2024',
 'Augusti 2025',
 'Utförde ett fem veckors feriearbete som innebar tungt fysiskt arbete med fokus på många armlyft. Arbetade på tvåskift (06.00-14.00 och 14.00-23.00), vilket visade flexibilitet och anpassningsförmåga. Genomgick en 3-timmarsutbildning i handtravers och hanterade material. Samarbetade effektivt med dagligen roterande kollegor, vilket visade stark teamkänsla. Tillgodogjorde mig kunskap om företagets rutiner, inklusive arbete med dator.',
 ARRAY['industry']::TEXT[],
 1,
 ARRAY['industri', 'tillverkning', 'fysiskt_arbete']::TEXT[],
 'entry',
 'physical',
 ARRAY['skiftarbete', 'handtravers', 'materialhantering', 'teamwork', 'flexibilitet']::TEXT[],
 ARRAY['anodisering', 'metallbearbetning', 'tvåskift', 'feriearbete']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Minerva University',
 'Stockholm, Sverige',
 'Alumni Ambassador Western Europe',
 'Sep 2024',
 'Pågående',
 '25% tjänst som jag planerar självständigt, med en arbetstid på cirka 40 timmar i månaden. Ansvarig för att genomföra strategisk marknadsföring genom resor till skolor och mässor i Västeuropa för att attrahera potentiella elever till ett amerikanskt universitet. Bygger och underhåller databaser för skolkontakter och söker aktivt upp kandidater genom olika akademiska forum. Detta inkluderar möten med SYO:er och studievägledare. Ansvarig för logistik som bokning av flyg, hotell och transporter för att täcka ett stort geografiskt område (hela Västra europa och Norden).',
 ARRAY['tech', 'customerservice', 'reception']::TEXT[],
 2,
 ARRAY['marknadsforing', 'forsaljning', 'utbildning', 'kundservice']::TEXT[],
 'intermediate',
 'hybrid',
 ARRAY['databaser', 'CRM', 'event_planering', 'reselogistik', 'B2B', 'internationell_kommunikation']::TEXT[],
 ARRAY['universitet_rekrytering', 'utlandsstudier', 'skolmässor', 'västeuropa', 'norden']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Linnea Moritz (linneamoritz.com)',
 'Stockholm, Sverige',
 'Konstnär och Egenföretagare',
 'Jan 2024',
 'Pågående',
 'Målar och säljer mina egna oljemålningar. 39 utställningar i 21 städer, 10 länder och 4 kontinenter. Vunnit tre första pris i jurybedömda konstutställningar (bl.a. Stockholms Konstsalong, Greenpoint Gallery Brooklyn). Driver all marknadsföring, bokföring, export, kundhantering och sociala medier självständigt. Förvaltar Shopify-butik med försäljning av originalkonst och konsttryck internationellt.',
 ARRAY['art']::TEXT[],
 3,
 ARRAY['konst', 'ehandel', 'entreprenor']::TEXT[],
 'expert',
 'remote',
 ARRAY['shopify', 'e-handel', 'bokforing', 'export', 'sociala_medier', 'sjalvstandig']::TEXT[],
 ARRAY['kubism', 'oljemålning', 'internationell_forsaljning', 'konsttryck']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'House of Beans, Hötorgshallen',
 'Stockholm, Sverige',
 'Försäljare/Barista',
 'Aug 2024',
 'Feb 2025',
 'Säljer te, kaffebönor och chokladpraliner i en butik i Hötorgshallen i Stockholm. Direktförsäljning till kunder och barista. Arbetar 8 timmar som ensam anställd i butiken, mycket eget ansvar.',
 ARRAY['restaurant', 'retail', 'customerservice']::TEXT[],
 4,
 ARRAY['butik', 'cafe', 'kundservice']::TEXT[],
 'intermediate',
 'physical',
 ARRAY['barista', 'forsaljning', 'kassahantering', 'sjalvstandigt_arbete']::TEXT[],
 ARRAY['kaffe', 'te', 'choklad', 'hotorgshallen']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Max Hamburgare',
 'Vetlanda, Sverige',
 'Restaurangbiträde',
 'April 2024',
 'Aug 2024',
 'Sommarjobbade på Max Hamburgare i Vetlanda. Drive-in, fritös, kök, servering, kassa, städ.',
 ARRAY['restaurant']::TEXT[],
 5,
 ARRAY['snabbmat', 'restaurang', 'kundservice']::TEXT[],
 'entry',
 'physical',
 ARRAY['drive_in', 'kassa', 'kokteknik', 'stadning', 'hogt_tempo']::TEXT[],
 ARRAY['snabbmat', 'sommarjobb', 'max_hamburgare']::TEXT[]
),
-- 2022-2023
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Keeping Tabs',
 'New York, USA',
 'Multimedia Technical Specialist',
 'Nov 2022',
 'Juni 2023',
 'Jag planerade och koordinerade en konstsamling för företaget, skapade en kollektion av målningar enligt företagets vision och mål, och målade oljemålningar som var anpassade för konstsmarknaden i New York. Fick djup förståelse för entreprenörskap, företagsutveckling och resursbegränsad problemlösning. Inom försäljning ansvarade jag för leadgenerering, orderleverans till kunder, fakturering, posthantering, e-handelsdrift och kundnöjdhet, samt ansvarade för HR, skatteberäkningar och ekonomi. Utvecklade relationer med försäljare inom NFT-branschen och bidrog till utvecklingen av företagets web3-strategi.',
 ARRAY['art', 'tech', 'customerservice']::TEXT[],
 6,
 ARRAY['konst', 'tech', 'forsaljning', 'entreprenorskap']::TEXT[],
 'advanced',
 'office',
 ARRAY['NFT', 'web3', 'e-handel', 'HR', 'ekonomi', 'leadgenerering', 'konstindustri']::TEXT[],
 ARRAY['blockchain', 'konstsamling', 'new_york', 'startup']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 '30 Campos Eliseos',
 'New York, USA',
 'Kubistisk målare',
 '2022',
 '2024',
 'Scoutad som professionell kubistmålare till prestigefylld konstsamlargrupp grundad i Florens. En av endast fem konstnärer utvalda bland 500+ sökande. Deltog i utställningar i New York, Dubai, Seoul, Madrid och Florens.',
 ARRAY['art']::TEXT[],
 7,
 ARRAY['konst', 'internationell']::TEXT[],
 'expert',
 'hybrid',
 ARRAY['kubism', 'internationella_utstallningar', 'konstsamlare', 'professionell_konstnar']::TEXT[],
 ARRAY['30_campos_eliseos', 'florens', 'lyxkonst', 'jurybedömd']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'TikTok / ByteDance',
 'Nashville, USA',
 'Kvalitetsgranskare Amerikanska marknaden',
 'Maj 2022',
 'Juni 2022',
 'Konsultjobb som kvalitetsgranskare: En kvalitetsgranskare granskar innehållsmoderatorernas arbete för att säkerställa att de följer riktlinjer och håller hög kvalitet i sitt arbete.',
 ARRAY['tech', 'qa', 'content_moderation']::TEXT[],
 8,
 ARRAY['tech', 'kvalitetskontroll', 'content_moderation']::TEXT[],
 'intermediate',
 'office',
 ARRAY['QA', 'content_policy', 'kvalitetssäkring', 'riktlinjer']::TEXT[],
 ARRAY['tiktok', 'bytedance', 'social_media']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'YouTube Ads - Kontrakt via rekryteringsföretaget Vaco',
 'San Francisco, USA',
 'Innehållsmoderatör - Svenska marknaden',
 'Feb 2022',
 'Juni 2022',
 'Som innehållsmoderator för YouTube-annonser hade jag ansvaret att flagga olämplig reklam och att aktivt bidra till att utöka databaser med olika exempel på markerade innehåll. Jag följde noggrant alla riktlinjer och arbetade tillsammans med andra svenskar i regelbundna möten för att diskutera och säkerställa att moderatorerna granskade materialet på korrekt sätt.',
 ARRAY['tech', 'content_moderation']::TEXT[],
 9,
 ARRAY['tech', 'content_moderation', 'svenska_marknaden']::TEXT[],
 'intermediate',
 'office',
 ARRAY['content_policy', 'svenska', 'databaser', 'teamwork']::TEXT[],
 ARRAY['youtube', 'google', 'annonsering']::TEXT[]
),
-- 2021
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Clubhouse - Kontrakt via rekryteringsföretaget Vaco',
 'Walnut Creek, USA',
 'Innehållsmoderatör - Skandinaviska och amerikanska marknaden',
 'Juni 2021',
 'Jan 2022',
 'Granskade Trust & Safety-ärenden inom samtliga 16 kategorier för en ljudbaserad social medieplattform, vilket inkluderade hatiskt tal, sexuell exploatering, våldsbejakande extremism, missbruk, hot, CSAM (child sexual abuse material) och falsk information. Identifierade brister i standardiserade arbetsrutiner, policys och processer för att driva förbättringar av policyn, och samarbetade med ledningen för att implementera positiva förändringar för vårat dagliga arbete. Jag hade det fulla ansvaret för att hantera alla ärenden inom den svenska, norska och danska marknaden. Ökade produktiviteten med 98% samtidigt som jag uppfyllde alla dagliga mål för tjänstenivåavtalet.',
 ARRAY['tech', 'content_moderation', 'trust_safety']::TEXT[],
 10,
 ARRAY['tech', 'trust_safety', 'skandinavien']::TEXT[],
 'advanced',
 'office',
 ARRAY['content_moderation', 'policy_forbattring', 'skandinaviska_sprak', 'ledarskap', 'produktivitet']::TEXT[],
 ARRAY['clubhouse', 'ljudbaserad_social_media', 'CSAM', 'extremism']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Svensk-amerikanska handelskammaren i San Francisco och Silicon Valley',
 'San Francisco, USA',
 'Marknadsföringspraktikant',
 'Juni 2021',
 'September 2021',
 'Byggde upp ett nätverk med över 100 svenska startups, enskilda individer, offentliga myndigheter, tillväxtföretag, ideella organisationer, institutioner och företag genom branschspecifika konferenser, seminarier och evenemang. Assisterade två svenska konsultkunder med skapandet av en databas med 120 relevanta försäljningsleads i USA. Under sommaren ökade jag handelskammarens nätverk med 20% genom en effektiv utåtriktad e-post- och LinkedIn-marknadsföringsstrategi. Organiserade en kräftskiva för nätverket i samarbete med Norska klubben för 80 skandinaver och amerikaner, med målet att bygga upp en starkare och mer samarbetsinriktad nordisk affärsmiljö i Silicon Valley.',
 ARRAY['marketing', 'sales', 'events', 'networking']::TEXT[],
 11,
 ARRAY['marknadsforing', 'forsaljning', 'natverk', 'evenemang']::TEXT[],
 'intermediate',
 'hybrid',
 ARRAY['LinkedIn', 'email_marketing', 'leadgenerering', 'event_planering', 'B2B', 'svenska_marknaden']::TEXT[],
 ARRAY['silicon_valley', 'handelskammare', 'startups', 'nordisk_affarsmiljo']::TEXT[]
),
-- 2020-2021
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Minerva University',
 'Tyskland och USA',
 'Handledare för examensprojekt',
 'Sep 2020',
 'Maj 2021',
 'Handledare för 45 studenter i deras capstone-projekt, ett betydande projekt som genomförs under de sista två åren fram till examen. Ledde workshops, undervisade i projektledning och tillhandahöll omfattande akademiskt stöd. Gav kvalitativ och kvantitativ återkoppling till över 90 Capstone-uppgifter och mer än 40 Capstone-lektioner, samt bidrog till generella förbättringar av uppsatsprocessen. Jag träffade studenterna varje vecka för att ge stöd och coachning samt betygsatte uppgifter och kurser.',
 ARRAY['education', 'mentorship', 'academic']::TEXT[],
 12,
 ARRAY['utbildning', 'handledning', 'ledarskap']::TEXT[],
 'advanced',
 'hybrid',
 ARRAY['projektledning', 'akademiskt_stod', 'coaching', 'bedomning', 'workshopledning']::TEXT[],
 ARRAY['capstone', 'universitet', 'mentorskap']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Preply',
 'USA',
 'Engelskalärare online',
 'Dec 2020',
 'Maj 2021',
 'Jag undervisade i engelska online som lärare för elever i Sverige och Colombia, inom åldersgruppen 21-80 år. Jag designade och utvecklade olika lärandeaktiviteter och följde hemsidans läroplan som en del av min undervisning.',
 ARRAY['education', 'teaching', 'online']::TEXT[],
 13,
 ARRAY['utbildning', 'sprak', 'distans']::TEXT[],
 'intermediate',
 'remote',
 ARRAY['engelska', 'online_undervisning', 'laroplansutveckling', 'vuxenutbildning']::TEXT[],
 ARRAY['preply', 'sprakundervisning', 'internationell']::TEXT[]
),
-- 2020
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Sizigi',
 'San Diego, USA',
 'Marknadsföringspraktikant',
 'Juni 2020',
 'Aug 2020',
 'Designade en affärsfallstävling som ett sätt att marknadsföra SiZiGi till studenter på universitet i USA.',
 ARRAY['marketing']::TEXT[],
 14,
 ARRAY['marknadsforing', 'evenemang']::TEXT[],
 'entry',
 'remote',
 ARRAY['tavlingsdesign', 'studentmarknadsforing', 'kreativ_marknadsforing']::TEXT[],
 ARRAY['sizigi', 'universitetsmarknadsforing']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Kvarngården äldreboende',
 'Vetlanda',
 'Timvikarie',
 'Maj 2020',
 'Sep 2020',
 'Omvårdnad, medicinhantering, måltidsassistans, aktiviteter och socialt stöd, dokumentation och rapportering, samarbete med vårdteam, städning och underhåll samt emotionellt stöd. Gav omsorg till äldre personer med demens, Alzheimer''s sjukdom och begränsad rörlighet. Jag följde noggrant alla covid-protokoll och arbetade både morgon- och kvällspass inom vården.',
 ARRAY['healthcare', 'elderly_care', 'vård']::TEXT[],
 15,
 ARRAY['vard', 'aldreomsorg', 'healthcare']::TEXT[],
 'intermediate',
 'physical',
 ARRAY['demens', 'alzheimers', 'medicinhantering', 'covid_protokoll', 'skiftarbete', 'dokumentation']::TEXT[],
 ARRAY['aldreboende', 'omsorg', 'begransad_rorlighet']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Nestlé Argentina',
 'Buenos Aires, Argentina',
 'Hållbarhetspraktikant',
 'Jan 2020',
 'March 2020',
 'Skapade en konsultationsrapport med affärsförslag för att skapa en mer hållbar leverantörskedja för förpackade livsmedel och drycker i Latinamerika.',
 ARRAY['sustainability', 'consulting']::TEXT[],
 16,
 ARRAY['hallbarhet', 'konsult', 'leveranskedja']::TEXT[],
 'intermediate',
 'office',
 ARRAY['hallbar_forpackning', 'supply_chain', 'rapportskrivning', 'livsmedel']::TEXT[],
 ARRAY['nestle', 'latinamerika', 'plastforpackning']::TEXT[]
),
-- 2019-2020
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Minerva Project',
 'Tyskland och Argentina',
 'Marknadsföring - Global Marketing Team',
 'Sep 2019',
 'April 2020',
 'Samarbetade med det globala marknadsföringsteamet för att öka antagningen till Minerva University. Vägledde och stöttade över 2000 sökande elever genom ansökningsprocessen och svarade på deras frågor via Intercom, med fokus på att erbjuda högkvalitativ kundservice. Anordnade ett rekryteringsevenemang i Norge, dit jag reste och gav en presentation om vårt utbildningsprogram.',
 ARRAY['marketing', 'customerservice', 'recruiting']::TEXT[],
 17,
 ARRAY['marknadsforing', 'kundservice', 'rekrytering']::TEXT[],
 'intermediate',
 'hybrid',
 ARRAY['Intercom', 'CRM', 'studentrekrytering', 'event_planering', 'presentationer', 'internationell']::TEXT[],
 ARRAY['universitet', 'global_marknadsforing', '40_lander']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Mas Palou',
 'Barcelona, Spanien',
 'Marknadsföringsprojekt',
 'Augusti 2019',
 'Augusti 2019',
 'Hjälpte ett hotell utanför Barcelona med marknadsföring; gjorde google ads, uppgraderade deras hemsida, anordnade photoshoots och skapade reklam som användes ett år framåt.',
 ARRAY['marketing', 'hospitality', 'digital']::TEXT[],
 18,
 ARRAY['marknadsforing', 'hotell', 'digital_marknadsforing']::TEXT[],
 'intermediate',
 'project',
 ARRAY['google_ads', 'webbdesign', 'fotografi', 'content_creation', 'hospitality']::TEXT[],
 ARRAY['vingard', 'barcelona', 'rustic_hotel']::TEXT[]
),
-- 2018-2019
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Google Ads - Kontrakt via rekryteringsföretaget Vaco',
 'Sunnyvale, USA',
 'Svensk innehållsanalytiker för gTech',
 'Maj 2018',
 'April 2019',
 'Förbättrade och granskade svensk annonsering med expertkunskap inom svensk kultur och språk enligt riktlinjer. Utförde extraktion och granskning av innehåll för över 100 annonser per dag för Google Ad Suggestions. Arbetade i USA och på distans i Indien, Sydkorea och Stockholm. Hanterade framgångsrikt tidszonskoordinering. Det svenska teamet uppnådde 100% mål för tjänstenivåavtalet; främjde positivt samarbete inom teamet.',
 ARRAY['tech', 'content_analyst', 'swedish', 'remote']::TEXT[],
 19,
 ARRAY['tech', 'content', 'svenska_marknaden', 'distansarbete']::TEXT[],
 'advanced',
 'remote',
 ARRAY['google_ads', 'content_granskning', 'svenska', 'tidszon_koordinering', 'SLA', 'kulturkunskap']::TEXT[],
 ARRAY['gtech', 'annonsering', 'global_team']::TEXT[]
),
-- 2017-2018
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Minerva Project',
 'San Francisco, USA',
 'Evenemangskoordinator och elevhemsvärd - Student Experience Team',
 'Sep 2017',
 'Maj 2018',
 'Såg till att det fanns planerade evenemang enligt schema och organiserade olika aktiviteter varje vecka - totalt tre evenemang i veckan. Var ansvarig för möten, budgetkontroll, närvaro, schemaläggning och marknadsföring. Organiserade en stadsskattjakt där studenter både upptäckte San Francisco och utvidgade sitt kontaktnät. Koordinerade gästföreläsare till universitetet och använde olika mjukvaruprogram för att säkerställa smidig eventlogistik, incheckning och närvarohantering.',
 ARRAY['events', 'studentlife', 'coordination']::TEXT[],
 20,
 ARRAY['evenemang', 'koordinering', 'community']::TEXT[],
 'intermediate',
 'office',
 ARRAY['event_planering', 'budget', 'schemaläggning', 'gastforelasar_koordinering', 'logistik', 'mjukvaruverktyg']::TEXT[],
 ARRAY['universitet', 'student_experience', 'community_building']::TEXT[]
),
-- 2017
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Vetlanda Kommun',
 'Ekenässjöns skola/förskola, Vetlanda',
 'Köksbiträde',
 '31 juli 2017',
 '20 aug 2017',
 'Assisterade vid matlagning och serverade.',
 ARRAY['food', 'kitchen', 'kommun']::TEXT[],
 21,
 ARRAY['kok', 'livsmedel', 'kommun']::TEXT[],
 'entry',
 'physical',
 ARRAY['matlagning', 'servering', 'skolkok']::TEXT[],
 ARRAY['forskola', 'kommunal_sektor']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'ICA Maxi Stormarknad',
 'Vetlanda, Sverige',
 'Kassapersonal, frukt och grönt',
 'Juni 2019',
 'Aug 2019',
 'Jobbade i kassan, självscanningen, frukt och grönt, charken och blomavdelningen.',
 ARRAY['retail', 'customerservice', 'food']::TEXT[],
 22,
 ARRAY['butik', 'kassa', 'livsmedel']::TEXT[],
 'intermediate',
 'physical',
 ARRAY['kassa', 'sjalvscanning', 'frukt_gront', 'chark', 'kundservice']::TEXT[],
 ARRAY['ICA', 'stormarknad', 'certifierad']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'ICA Maxi Stormarknad',
 'Vetlanda, Sverige',
 'Kassapersonal, frukt och grönt',
 'Juni 2017',
 'Aug 2017',
 'Jobbade i kassan, självscanningen, frukt och grönt, charken och blomavdelningen.',
 ARRAY['retail', 'customerservice', 'food']::TEXT[],
 23,
 ARRAY['butik', 'kassa', 'livsmedel']::TEXT[],
 'intermediate',
 'physical',
 ARRAY['kassa', 'sjalvscanning', 'frukt_gront', 'chark', 'kundservice']::TEXT[],
 ARRAY['ICA', 'stormarknad', 'certifierad']::TEXT[]
),
-- 2016
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Wallby Säteri',
 'Vetlanda, Sverige',
 'Gårdsvärd',
 '27 jun 2016',
 '15 aug 2016',
 'Arbetade i receptionen med olika administrativa uppgifter, inklusive att ta emot bokningar, svara på telefonsamtal, hjälpa till med in- och utcheckning samt hantera betalningar. Assisterade vid caféet och bidrog till allmän städning.',
 ARRAY['reception', 'hospitality', 'customerservice']::TEXT[],
 24,
 ARRAY['reception', 'hotell', 'kundservice']::TEXT[],
 'entry',
 'physical',
 ARRAY['reception', 'bokningar', 'telefon', 'incheckning', 'betalningar', 'cafe']::TEXT[],
 ARRAY['sateri', 'landsbygdsturism']::TEXT[]
),
-- 2015
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'ICA Maxi Stormarknad',
 'Värmdö, Sverige',
 'Kassapersonal, frukt och grönt',
 '24 mars 2015',
 '9 aug 2015',
 'Arbetade i kassan samt självskanningen i den nybyggda butiken som öppnades den 13e mars 2013.',
 ARRAY['retail', 'customerservice', 'food']::TEXT[],
 25,
 ARRAY['butik', 'kassa', 'livsmedel']::TEXT[],
 'entry',
 'physical',
 ARRAY['kassa', 'sjalvscanning', 'nyoppnad_butik']::TEXT[],
 ARRAY['ICA', 'stormarknad']::TEXT[]
),
-- 2014-2015
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Siggesta Gård',
 'Värmdö, Sverige',
 'Gårdsvärd',
 '2014',
 '2015',
 'Jobbade med kundbemötande på en stor evenemangsanläggning på Värmdö (minigolf, restauranger, djurhållning, parker, småbutiker, konferancer, konserter, marknader och hotell). Hade en överseende roll där jag ansvarade för kommunikationen mellan de olika avdelningarna. Ansvarade för en marknad med cirka tusen deltagare varje Söndag. Tog mycket initiativ och såg till att besökare kände sig välkomna. Trädgårdsarbete och grönytearbete. Klippte gräs på hotellgräsmattan, samt rensade ogräs på minigolften samt fotbollsgolften. Jag klippte buskar, planeterade blommor, krattade, målade skyltar, och tok hand om all skräpsortering på gården. Körde golfbil inom arbetet för att transportera trädgårdsmaterial samt återvinning. Tog mycket initiativ och hade en god överblick över hela anläggningen.',
 ARRAY['events', 'outdoor', 'customerservice', 'trädgård']::TEXT[],
 26,
 ARRAY['evenemang', 'tradgard', 'kundservice', 'utomhus']::TEXT[],
 'intermediate',
 'physical',
 ARRAY['eventkoordinering', 'tradgardsarbete', 'kommunikation_mellan_avdelningar', 'initiativtagande', 'marknad', 'golfbil']::TEXT[],
 ARRAY['evenemangsanlaggning', 'stor_skala', 'multipel_verksamhet']::TEXT[]
),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Coffeehouse by George',
 'Nacka, Sverige',
 'Cafépersonal',
 '2014',
 '2015',
 'Kassahantering, kundbemötande, barista, matberedning och servering.',
 ARRAY['cafe', 'barista', 'customerservice']::TEXT[],
 27,
 ARRAY['cafe', 'barista', 'kundservice']::TEXT[],
 'entry',
 'physical',
 ARRAY['barista', 'kassa', 'matberedning', 'servering']::TEXT[],
 ARRAY['cafe', 'kaffespecialist']::TEXT[]
)
ON CONFLICT DO NOTHING;

-- ============================================
-- VOLUNTEER WORK (8 organizations in chronological order)
-- ============================================
INSERT INTO user_volunteer (user_id, organization, dates, bullets, sort_order) VALUES
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'LEAF (Living Environment and Future)',
 '2016 - 2017',
 ARRAY[
   'Ledde en elevgrupp vars mål var att utbilda skolan i bättre miljötänk. Organiserade presentationer, arbetsgrupper och information-kampanjer om hållbar utveckling under loppet av ett år',
   'Skapade ett modemagasin med modeller från olika nationaliteter för att marknadsföra kläder och smycken vars försäljning sponsrade ett hållbart jordbruksprojekt i Ghana. Samlade totalt in 30,000 kronor. Modemagasinet jag skapade är nu en årlig tradition på skolan',
   'Åkte på lokala konferenser om hållbarhet, och organiserade ett utbildningsläger för lågstadielever om återvinning och klimatfrågor'
 ]::TEXT[],
 1),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Finimize',
 '2016 - 2017',
 ARRAY[
   'Eventkoordinator: Organiserade det allra första Finimize Community-evenemanget i Argentina, en paneldebatt om FinTech',
   'Ansvarade för e-postmarknadsföring, samlade in evenemangsdata och schemalade intervjuer'
 ]::TEXT[],
 2),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'The Right Solution Project',
 'Mars 2013 – April 2015',
 ARRAY[
   'Tog initiativ att finansiera en ideell organisation för kvinnors utbildning vid 15 års ålder. Vi samlade in över 120,000 kr genom evenemang, konstutställningar och försäljning av min konst, samt matchade donationer',
   'Tillhandahöll över 400 vårdpaket med smärtstillande medel och kvinnliga hygienprodukter till Etiopiska skolor'
 ]::TEXT[],
 3),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'India Unlimited Utbytesprogram',
 'Nov 2014 - Feb 2015',
 ARRAY[
   'Jag deltog i ett EU-baserat projekt för att främja fredliga relationer mellan Sverige och Indien. Som representant för min skola reste jag till Indien och samordnade även elever från systerskolan som besökte Stockholm',
   'Koordinerade ett hygienprojekt i Indien, fick värdefull kunskap om hållbar utveckling i arbete i utvecklingsländer'
 ]::TEXT[],
 4),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Vi Unga Stockholm',
 '5 Augusti 2013 - 11 Jan 2014',
 ARRAY[
   'Entreprenör i skärgården - genomförde Vi Unga Stockholms läns utbildningsprogram "Do it yourself" (5-9 augusti 2013)',
   'Idégenerering och nytänkande, planering och formulering av syfte/mål/målgrupp för projekt',
   'Budgetläggning och distanskommunikation',
   'Personligt ledarskap',
   'Lärde mig att kommersialisera min konst och började sälja på marknader samt ta porträttbeställningar'
 ]::TEXT[],
 5),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Värmdö Församling',
 '2012 - 2014',
 ARRAY[
   'Var ledare för 3 olika konfirmandgrupper under loppet av 2 år. Var ledare på ett tre veckors sommarläger, hjälpte till att organisera aktiviteter och att hålla i diskussionsgrupper',
   'Ledare konfirmationsläger på skärgårdsön Ängsholmen 2-25 Juli 2013',
   'Svenska Kyrkan: Ledarskapskurs steg 1 och 2'
 ]::TEXT[],
 6),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Princess Hall Stockholm',
 'Augusti 2017',
 ARRAY[
   'Konstnär: Planerade, organiserade och marknadsförde egen konstutställning i Stockholm',
   'Sålde originella tavlor och tryck för cirka 20,000 kronor'
 ]::TEXT[],
 7),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Chinese Language Summer Camp, Beijing Sports University',
 '3 Juli - 14 Juli 2016',
 ARRAY[
   'Utbyteresa till Beijing, undervisning inom Kinesiskt språk och kultur',
   'Vann resan genom att komma tredjeplats i tävlingen "Chinese Bridge, Chinese Proficiency Competition for foreign students" Bergen, Norge, Mars 2016'
 ]::TEXT[],
 8)
ON CONFLICT DO NOTHING;

COMMIT;


-- ============================================
-- PART 2: Awards, Certifications, Tech Projects, Skills
-- ============================================

BEGIN;

-- ============================================
-- AWARDS (11 total in chronological order)
-- ============================================
INSERT INTO user_awards (user_id, award_text, sort_order) VALUES
('da8ed517-3b67-4456-8831-6ed3cb7114ad', '1:a pris Stockholms Konstsalong 2024 - Jurybedömd utställning, nominerad "Publikens Favorit"', 1),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', '1:a pris Greenpoint Gallery Brooklyn 2023 - Vann bland 60 konstnärer, fick solorutställning', 2),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', '1:a pris Murray''s Creative Contest 2022 - Detroit-baserad tävling med specialdesign', 3),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Scoutad som professionell kubistisk målare till 30 Campos Eliseos (5 av 500+ sökande) - 2022', 4),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'L''Oréal Brandstorm 2020 - Utvecklade plasticfri förpackningslösning för Garnier', 5),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Global Startup Weekend Stockholm - Vinnare för Terra Finance (Google for Startups & Techstars) - Augusti 2019', 6),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Minerva University Award for Initiative 2018', 7),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Röda Korsets diplom - Guldutmärkelse för teamwork och ledarskap (100+ volontärtimmar) - 2017', 8),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Sålde konst för 20,000 kr på Princess Hall-utställning i Stockholm - Augusti 2017', 9),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Tredje pris Chinese Bridge 2016 - Nationell tävling i kinesiskt språk, Bergen', 10),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', '39 konstutställningar i 21 städer, 10 länder och 4 kontinenter', 11)
ON CONFLICT DO NOTHING;

-- ============================================
-- CERTIFICATIONS (10 general certifications)
-- ============================================
INSERT INTO user_certifications (user_id, certification_name, issuing_organization, sort_order) VALUES
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'B-körkort (automat)', 'Transportstyrelsen', 1),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'ICA kassahantering', 'ICA Maxi Stormarknad', 2),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Trygga mat', 'ICA', 3),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Röda Korset första hjälpen (12 timmar)', 'Röda Korset Norge', 4),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Handtravers (3 timmar)', 'Profilgruppen', 5),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'ICA Banken Penningtvätt (lagkrav)', 'ICA Banken', 6),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Säkerhet i butik (ICA Krav)', 'ICA', 7),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'ICA''s goda affärer för butik (ICA Krav)', 'ICA', 8),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'ICA handlar för miljön', 'ICA', 9),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Svenska Kyrkan Ledarskapskurs steg 1 och 2', 'Svenska Kyrkan', 10)
ON CONFLICT DO NOTHING;

-- ============================================
-- TECH CERTIFICATIONS (7 with verification URLs)
-- ============================================
INSERT INTO tech_certifications (user_id, certification_name, issuer, year_obtained, credential_url, sort_order) VALUES
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Introduction to Python', 'DataCamp', 2022, 'https://www.datacamp.com/completed/statement-of-accomplishment/course/b48391ada93ca5d05574753a080433a38613cbb1', 1),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Intermediate SQL Queries', 'DataCamp', 2021, 'https://www.datacamp.com/completed/statement-of-accomplishment/course/39b604029392a524860d0b1b01770fd40daca6ea', 2),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Joining Data in SQL', 'DataCamp', 2022, 'https://www.datacamp.com/statement-of-accomplishment/course/716134e07e88965583ff3a22ec5b0331fefb5ab3', 3),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Credit Risk Modeling in Python', 'DataCamp', 2021, 'https://www.datacamp.com/completed/statement-of-accomplishment/course/7a7b44fbb09e0d53fd6a316cb6be3d95b89ad054', 4),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Portfolio Risk Management in Python', 'DataCamp', 2021, 'https://www.datacamp.com/completed/statement-of-accomplishment/course/300ccf35d18836e5febcfe983ed849e277bc958d', 5),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Foundations: Data, Data, Everywhere', 'Google via Coursera', NULL, 'https://www.coursera.org/account/accomplishments/certificate/RKCK36NMMFRY', 6),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'Blockchain for Business', 'Udemy', 2021, 'https://www.udemy.com/certificate/UC-d788d078-ea05-49fc-bc2a-e93f455dd0d1/', 7)
ON CONFLICT DO NOTHING;

-- ============================================
-- TECH PROJECTS (11 production apps)
-- ============================================
INSERT INTO tech_projects (user_id, project_name, description, tech_stack, live_url, year, highlights, sort_order) VALUES
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'CBAM-Validator',
 'Reaktivt frågeformulär för svenska företag som importerar varor. Hjälper företag att följa EU:s kolbaserade gränsskatt (CBAM). Multi-steg formulär med villkorlig logik.',
 ARRAY['TypeScript', 'Next.js', 'Reactive Forms']::TEXT[],
 'https://cbam-validator.vercel.app/',
 2026,
 ARRAY['Lansering 25 feb 2026', 'Multi-steg formulär', 'EU-regler CBAM']::TEXT[],
 1),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'NordiqFlow',
 'Flerproduktsplattform för svensk arbetsmarknadsintelligens med verktyg för karriärövergångar, kompetensanalys och kommunal utbildningsdata.',
 ARRAY['Python', 'Next.js', 'React', 'API Integration']::TEXT[],
 'https://nordiqflow.vercel.app/',
 2025,
 ARRAY['SCB arbetsmarknadsdata', 'AI-driven matchning', 'Kommunal analys']::TEXT[],
 2),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Linneas Konstbutik',
 'E-handelsplattform med försäljning av original kubistiska oljemålningar internationellt. Automatisering för Pinterest-marknadsföring och AI-produktrekommendationer.',
 ARRAY['Shopify', 'Pinterest API', 'Anthropic API', 'Automation']::TEXT[],
 'https://linneamoritz.com/',
 2024,
 ARRAY['Internationell e-handel', 'Pinterest automation', 'AI-produktbeskrivningar']::TEXT[],
 3),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Smålands Företagskarta',
 'Interaktiv dashboard som visualiserar företagsdata för alla 13 kommuner i Jönköpings län. Byggd för Science Park, Almi och kommuner.',
 ARRAY['Next.js 14', 'TypeScript', 'Recharts', 'Framer Motion']::TEXT[],
 'https://smalands-foretagskarta.vercel.app/',
 2025,
 ARRAY['Interaktiv SVG-karta', '13 kommuner', 'Kvartalsuppdateringar']::TEXT[],
 4),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'AK Städservice',
 'Komplett företagshemsida för Stockholmsbaserat B2B-städföretag. SEO-optimerad för Google och AI-verktyg.',
 ARRAY['Next.js', 'React', 'Tailwind CSS', 'SEO']::TEXT[],
 'https://akstadservice.vercel.app/',
 2025,
 ARRAY['Byggd på 2 dagar', 'B2B-fokus', 'AI-SEO optimerad']::TEXT[],
 5),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Provence Bike Touring',
 'Ruttplaneringsplattform för självständiga cykelturister i Provence. Interaktiv karta med POI-lager, höjdprofiler och GPX-export.',
 ARRAY['React', 'Mapbox GL JS', 'PostGIS', 'OpenStreetMap']::TEXT[],
 'https://provencebiking.vercel.app/',
 2025,
 ARRAY['Mapbox GL JS', 'PostGIS queries', 'Swipeable mobile UI']::TEXT[],
 6),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 '10K Race Finder — Europe 2026',
 'Verktyg för att hitta och bokmärka 10K-lopp i Europa. 38 kurerade lopp med localStorage favoriter.',
 ARRAY['React 18', 'Vite 5', 'localStorage', 'IntersectionObserver']::TEXT[],
 'https://10krunningeurope.vercel.app/',
 2026,
 ARRAY['38 europeiska lopp', 'localStorage favoriter', 'Multi-country']::TEXT[],
 7),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Bidragsguiden',
 'AI-driven webbapp för att hitta företagsbidrag. Interaktivt quiz som matchar svenska företagare mot relevanta bidrag från Tillväxtverket, Vinnova, EU-fonder.',
 ARRAY['Next.js 14', 'Claude API', 'Supabase', 'Vercel']::TEXT[],
 'https://bidragsguiden.vercel.app/',
 2025,
 ARRAY['Live i produktion', 'Används av svenska företag', 'EU compliance']::TEXT[],
 8),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Backspegeln',
 'Skräck-temat körkortsquiz med pseudo-3D grafik. Svara rätt på svenska körkorsfrågor för att överleva.',
 ARRAY['React 19', 'Vite 6', 'Tone.js', 'Canvas API']::TEXT[],
 'https://backspegeln.vercel.app/',
 2025,
 ARRAY['Interaktivt spel', 'Äkta Trafikverket-frågor', 'Web Audio synthesis']::TEXT[],
 9),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Digitala Produktpass',
 'Quiz-baserat verktyg som hjälper svenska tillverkare generera EU-kompatibla Digitala Produktpass med AI.',
 ARRAY['Next.js 14', 'TypeScript', 'Claude API', 'jsPDF']::TEXT[],
 NULL,
 2025,
 ARRAY['EU ESPR 2024/1781', 'AI-genererade pass', 'PDF + QR-kod']::TEXT[],
 10),
('da8ed517-3b67-4456-8831-6ed3cb7114ad',
 'Anna Levitova Portfolio',
 'Marknadsföringswebbplats för PR-strateg. Flerspråkigt stöd (EN/DE/RU) med glassmorfism-design.',
 ARRAY['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion']::TEXT[],
 'https://pinkportfolio.vercel.app/',
 2025,
 ARRAY['Flerspråkig (EN/DE/RU)', 'Glassmorfism', 'Framer Motion animations']::TEXT[],
 11)
ON CONFLICT DO NOTHING;

-- ============================================
-- SKILLS (60+ total)
-- ============================================
INSERT INTO user_skills (user_id, category, skill_type, skill_text) VALUES
-- LANGUAGES
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Svenska (Modersmål)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Engelska (flytande)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Norska (professionellt)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Danska (professionellt)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Mandarin (HSK nivå 3)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Tyska (grundläggande)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Spanska (grundläggande)'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'all', 'language', 'Franska (grundläggande)'),
-- PROGRAMMING
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Python'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'TypeScript'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'JavaScript'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'SQL'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'R'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'HTML/CSS'),
-- FRAMEWORKS
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'React'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Next.js'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Tailwind CSS'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Node.js'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'NumPy'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Pandas'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Framer Motion'),
-- APIs
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Gmail API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Shopify API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Pinterest API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Anthropic API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Claude API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'OpenAI API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Google Sheets API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Mapbox GL JS'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'OpenStreetMap'),
-- PLATFORMS
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Vercel'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Shopify'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'GitHub'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'PostgreSQL'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'PostGIS'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Supabase'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Tableau'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Google Analytics'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Intercom'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'CRM-system'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Canva'),
-- MARKETING
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Google Ads'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Facebook Ads'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Content SEO'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Excel/Google Sheets'),
-- SPECIALTIES
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Machine Learning'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Web3/Blockchain'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'OAuth'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'GIS & Kartvisualisering'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Canvas API'),
('da8ed517-3b67-4456-8831-6ed3cb7114ad', 'tech', 'technical', 'Tone.js')
ON CONFLICT DO NOTHING;

COMMIT;
